# removed osx support as osx has clang 4.0 and can't run docker inside travis
# removed windows support as windows cannot run docker inside travis

jobs:
  include:
    - os: linux
      dist: bionic
      arch: arm64
#    - os: linux
#      dist: bionic
#      arch: ppc64le
    - os: linux
      dist: bionic
      arch: arm
    - os: linux
      dist: bionic
      arch: armv7
    - os: linux
      dist: bionic
      arch: amd64

# "pip3 install onnx" builds locally, which needs "protobuf-compiler" and "libprotoc-dev" to compile
# ref: https://github.com/onnx/onnx/issues/133#issuecomment-339457553

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - protobuf-compiler
    - libprotoc-dev

language: bash

script:
  # bug: numpy 1.18 fails
  # - pip3 install numpy onnx
  - pip3 install numpy==1.15.0 onnx==1.5.0
  - make all
