jobs:
  include:
    - os: osx
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: arm
    - os: linux
      dist: bionic
      arch: armv7

# "pip3 install onnx" builds locally, which needs "protobuf-compiler" and "libprotoc-dev" to compile
# ref: https://github.com/onnx/onnx/issues/133#issuecomment-339457553

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - protobuf-compiler
    - libprotoc-dev
  homebrew:
    update: true
    packages:
    - python
    - swig
    - doxygen
    - clang-format

language: bash

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install --with-clang llvm; fi

script:
  - pip3 install numpy onnx
  - make all