arch:
  - amd64
  - ppc64le
  - arm64
  - armv7
  - arm

dist: bionic

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - llvm-8-dev

language: bash

script:
  - pip3 install numpy onnx
  - make