# os:
#   - bionic
#   - osx

# env:
#   - BADGE=linux
#   - BADGE=osx

# hack to get some OS-specific badges
# matrix:
#   exclude:
#     - os: linux
#       env: BADGE=osx
#     - os: osx
#       env: BADGE=linux

# dist: bionic
jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64
   - os: linux
    arch: ppc64le
   - os: linux
     arch: s390x

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - llvm-8-dev

language: bash
script:
  - pip3 install numpy onnx
  - make