# removed osx support as osx has clang 4.0 and can't run docker inside travis
jobs:
  include:
    - os: windows
      language: sh
      python: "3.7"
      services:
        - docker
      before_script:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: arm
    - os: linux
      dist: bionic
      arch: armv7

# "pip3 install onnx" builds locally, which needs "protobuf-compiler" and "libprotoc-dev" to compile
# ref: https://github.com/onnx/onnx/issues/133#issuecomment-339457553

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - protobuf-compiler
    - libprotoc-dev

language: bash

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python buildDocker.py; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip3 install numpy onnx ; make all; fi