jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: bionic
      arch: ppc64le
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: bionic
      arch: armv7
    - os: linux
      dist: bionic
      arch: arm
    - os: osx

addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
  homebrew:
    update: true
    packages:
    - llvm-8-dev
    - build-essential
    - python3.6-dev
    - python3-pip
    - python3-setuptools
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - llvm-8-dev

language: bash

script:
  - pip3 install numpy onnx
  - make