arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
# os: linux
dist: bionic
addons:
  apt:
    update: true
    packages:
    - build-essential
    - python3.6-dev
    - python3-pip
    - swig
    - doxygen
    - clang-format
    - clang
    - clang-8
    - llvm-8
    - llvm-8-dev

language: bash
script:
  - pip3 install numpy onnx
  - make