name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you so much for filing the issue. We will look at it and take appropriate action as soon as possible.'' first issue'
        pr-message: 'Thank you for your first contribution to deepC. Much appreciated. 🙏'' first pr'
